**Original Folder:** suicide_watch-database\PRAW\count_data

In [1]:
import pandas as pd

In [2]:
available_batches = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
df_all = pd.DataFrame()
for batch_number in available_batches:
    df = pd.read_csv(f"batch{batch_number}_sub_comments_count.csv")
    df_all = pd.concat([df_all, df], ignore_index=True)
df_all

,username,counts
0,---feelingalone---,"{""SuicideWatch"": 9}"
1,-anonymously,"{""SuicideWatch"": 7}"
2,-crave,"{""ElectroBOOM"": 2, ""ImTheMainCharacter"": 1, ""t..."
3,-dogtopus-,"{""CookingCircleJerk"": 4, ""BestofRedditorUpdate..."
4,-ForPrivacy-,"{""SuicideWatch"": 7}"
...,...,...
218813,brooklynhils,"{""Methadone"": 16, ""adhdwomen"": 5, ""DiagnoseMe""..."
218814,burn_the_damnaccount,{}
218815,iamabovethehill,{}
218816,Low-Strength0806,"{""SuicideWatch"": 1}"
218817,NoMorePleasze,{}

In [3]:
df_all.to_csv("all_batches_sub_comments_count.csv", index=False)

In [4]:
available_batches = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
df_all = pd.DataFrame()
for batch_number in available_batches:
    df = pd.read_csv(f"batch{batch_number}_sub_posts_count.csv")
    df_all = pd.concat([df_all, df], ignore_index=True)
df_all

,username,counts
0,---feelingalone---,"{""SuicideWatch"": 1}"
1,-anonymously,"{""SuicideWatch"": 1}"
2,-crave,"{""OopsThatsDeadly"": 1, ""tonightsdinner"": 2, ""m..."
3,-dogtopus-,"{""NoStupidQuestions"": 1, ""TheGirlSurvivalGuide..."
4,-ForPrivacy-,"{""SuicideWatch"": 1}"
...,...,...
218813,brooklynhils,"{""medical_advice"": 2, ""DermatologyQuestions"": ..."
218814,burn_the_damnaccount,"{""SuicideWatch"": 1}"
218815,iamabovethehill,{}
218816,Low-Strength0806,"{""SuicideWatch"": 1}"
218817,NoMorePleasze,{}

In [5]:
df_all.to_csv("all_batches_sub_posts_count.csv", index=False)